### ISSUE TITLE
`%i` format code yields full ISO-8601 date-time

### ISSUE THREAD

**Issue by hollasch** [hollasch/timeprint#48]
Equivalent to `%Y-%m-%dT%H:%M:%S%z`.

**Comment by hollasch** [comment]
`%id` is basically `%F`, and `%it` is basically %T, so we don't need the subtypes `%id` or `%it`.

Given this, `%i` would be equivalent to the shorter `%FT%T%z`.

**Comment by sergeevabc** [comment]
Dear @hollasch,

Windows 7 user here who is looking for a _easy way_ to get [ISO8601](https://unix.stackexchange.com/questions/164826/date-command-iso-8601-option)-like timestamp (and save it as a variable to use further within various scripts). Unfortunately, `timeprint` produces the least desirable timestamp by default: `Thursday, May 01, 2025 01:02:03`.  For example, [Busybox](https://frippery.org/busybox/) `date -Iseconds` outputs `2025-05-01T01:02:03+04:00` and [Coreutils](https://github.com/uutils/coreutils) `date --rfc-3339 seconds` outputs `2025-05-01 01:02:03+04:00`, but it is not very readable. Some mumbo-jumbo is required: `busybox date "+%Y-%m-%d %H:%M:%S"`.

Perhaps you could add some switch to get `2025-05-01 01:02:03`.

**Comment by hollasch** [comment]
@sergeevabc — You can accomplish this with `"%F %T"`.

If you'd like a single script with no parameters, you can use the following single-line CMD script:

    @timeprint "%F %T"

Or, if you want to use an environment variable:

    @timeprint "%MyTimeFormat%"

**Comment by sergeevabc** [comment]
It works as expected now.
God bless you, Steve.
